FROM wordpress:latest

# Install WP-CLI
RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && \
    chmod +x wp-cli.phar && \
    mv wp-cli.phar /usr/local/bin/wp

# Copy custom plugins
COPY wp-content/plugins/directcargo-headless /var/www/html/wp-content/plugins/directcargo-headless

# Set proper permissions
RUN chown -R www-data:www-data /var/www/html

EXPOSE 80
